### ISSUE TITLE
Unable to find Lifx Mini Day & Dusk bulbs

### ISSUE THREAD

**Issue by tdawson** [mrstegeman/lifx-adapter#14]
I have a selection of different Lifx bulbs.  Several A19, a couple BR30, and a couple Mini Day & Dusk bulbs.
The A19 and BR30 bulds are discoverable and usable via the lifx-adapter for mozilla-iot-gateway.  But the Mini Day & Dusk bulbs do not show up when I scan for things.
Can this be fixed so they show up.

**Comment by mrstegeman** [comment]
Thanks for reporting! I was able to reproduce and fix the issue. If you update your add-on to v0.2.0, you should be able to find your bulb.
