### ISSUE TITLE
Transfer repo to mrstegeman

### ISSUE THREAD

**Issue by mrstegeman** [mrstegeman/lifx-adapter#15]
I'm guessing you're no longer using the Mozilla IoT gateway software, as it seems that you're no longer maintaining this repo. Would you mind if we pull it into the mozilla-iot organization so that we can keep it updated?

**Comment by steveatinfincia** [comment]
That would be fine with me, I'm way too sick to maintain anything at the moment. I'll go ahead and transfer the repo now :)

**Comment by steveatinfincia** [comment]
Ah, I can't do that automatically it seems, were you just going to pull the git history or did you want to actually transfer the Github repo itself?

**Comment by mrstegeman** [comment]
I’m sorry to hear that! I hope you recover soon.

Would you want to just transfer it to my account instead? I’d be happy to transfer it back in the future if you decide you want to maintain it again.

**Comment by mrstegeman** [comment]
Thank you!
