### ISSUE TITLE
LIFX 1000 with missing properties

### ISSUE THREAD

**Issue by agentff6600** [mrstegeman/lifx-adapter#16]
I have 4 LIFX that only show up with the on/off and the color property. Could it be that the LIFX 1000 are too old or what might be the problem?

**Comment by stripTM** [comment]
I asked the same thing for Yeelight and here they spoke https://github.com/mrstegeman/lifx-adapter/pull/12

**Comment by mrstegeman** [comment]
Duplicates #10
