### ISSUE TITLE
Implementation of FadeAction

### ISSUE THREAD

**Issue by soulfire03** [mrstegeman/lifx-adapter#18]
Hello,
Could you please add an implementation of FadeAction to be able to ramp up and down the light over a specified amount of time?

Thanks!

**Comment by soulfire03** [comment]
Thank you for your work! This is working great for adhoc queries. 
However I thought the feature would work in rules also. I don't see the fade action in rules.

**Comment by mrstegeman** [comment]
Unfortunately, that’s something we still have to implement: https://github.com/WebThingsIO/gateway/issues/996
